version: '3.9'
services:
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_api_instances:/evolution/instances
    depends_on:
      - evolution-api-redis
      - evolution-api-postgres
  
  evolution-api-redis:
    image: redis:latest
    networks:
      - evolution-net
    container_name: redis
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_api_redis_data:/data
    ports:
      - 6379:6379

  evolution-api-postgres:
    container_name: evolution-api-postgres
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_NAME=evolution
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

  evolution_api_pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - evolution-net
    environment:
      - PGADMIN_DEFAULT_EMAIL=email@example.com
      - PGADMIN_DEFAULT_PASSWORD=123456  
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 4000:80
    depends_on:
      - evolution-api-postgres

volumes:
  evolution_api_instances:
  evolution_api_postgres_data:
  evolution_api_pgadmin_data:
  evolution_api_redis_data:


networks:
  evolution-net:
    name: evolution-net
    driver: bridge

  
